# Generated by Django 5.2.17 on 2026-09-06 21:38

import apps.people.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministrativeSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9_]+$", "Use letras, números y guion bajo."
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "sistema administrativo",
                "verbose_name_plural": "sistemas administrativos",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curp",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[apps.people.validators.validate_curp],
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=250)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("INACTIVE", "Inactivo"),
                            ("UNKNOWN", "No informado"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "persona",
                "verbose_name_plural": "personas",
                "ordering": ("curp",),
            },
        ),
        migrations.CreateModel(
            name="PersonSystemMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "pertenencia administrativa",
                "verbose_name_plural": "pertenencias administrativas",
            },
        ),
    ]
