# Generated by Django 5.2.17 on 2026-09-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personsystemmembership",
            name="first_seen_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships_first_seen",
                to="sources.payrollimport",
            ),
        ),
        migrations.AddField(
            model_name="personsystemmembership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_memberships",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="personsystemmembership",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="people.administrativesystem",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="systems",
            field=models.ManyToManyField(
                blank=True,
                related_name="people",
                through="people.PersonSystemMembership",
                to="people.administrativesystem",
            ),
        ),
        migrations.AddConstraint(
            model_name="personsystemmembership",
            constraint=models.UniqueConstraint(
                fields=("person", "system"), name="unique_person_system"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(("curp__regex", "^[A-Z0-9]{18}$")),
                name="people_person_curp_basic_format",
            ),
        ),
    ]
