# Generated by Django 5.2.17 on 2026-09-06 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("relative_path", models.CharField(max_length=500)),
                ("extension", models.CharField(max_length=8)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("detected_prefix", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Presente"),
                            ("MISSING", "No encontrado en la última verificación"),
                            ("UNEXPECTED", "Nombre o ubicación inesperada"),
                        ],
                        default="PRESENT",
                        max_length=12,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "archivo TIFF",
                "verbose_name_plural": "archivos TIFF",
                "ordering": ("relative_path",),
                "permissions": [
                    ("inventory_tiff", "Puede inventariar TIFF en modo lectura")
                ],
            },
        ),
        migrations.CreateModel(
            name="DigitalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_mode",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL_ONE_SIDE", "Individual una cara"),
                            ("INDIVIDUAL_DUPLEX", "Individual doble cara / METLIFE"),
                            ("MULTI_ONE_SIDE", "Multi una cara"),
                            ("OTHER", "Otra"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "other_mode_description",
                    models.CharField(blank=True, max_length=200),
                ),
                ("sequence", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "classification_confirmed_at",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
            options={
                "verbose_name": "documento lógico",
                "verbose_name_plural": "documentos lógicos",
                "ordering": ("sequence", "pk"),
            },
        ),
        migrations.CreateModel(
            name="DigitalInventoryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("root_relative_path", models.CharField(max_length=500)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("compute_hashes", models.BooleanField(default=False)),
                ("discovered_count", models.PositiveIntegerField(default=0)),
                ("unexpected_count", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "ejecución de inventario TIFF",
                "verbose_name_plural": "ejecuciones de inventario TIFF",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9_-]+$",
                                "Use letras, números, guion o guion bajo.",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("destination_folder", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "tipo documental",
                "verbose_name_plural": "tipos documentales",
                "ordering": ("sort_order", "code"),
            },
        ),
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("workstation", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activa"),
                            ("COMPLETED", "Terminada"),
                            ("ABORTED", "Interrumpida"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "sesión de digitalización",
                "verbose_name_plural": "sesiones de digitalización",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="BatCsvImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file_name", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completada"),
                            ("WITH_ERRORS", "Completada con errores"),
                        ],
                        max_length=16,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("accepted_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bat_imports",
                        to="batches.intakebatch",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bat_csv_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "importación CSV del BAT",
                "verbose_name_plural": "importaciones CSV del BAT",
                "ordering": ("-imported_at",),
                "permissions": [
                    ("import_bat_csv", "Puede importar resúmenes CSV del BAT")
                ],
            },
        ),
        migrations.CreateModel(
            name="BatCsvRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("curp", models.CharField(blank=True, max_length=18)),
                ("physical_count", models.PositiveIntegerField(blank=True, null=True)),
                ("digital_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "individual_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("multi_count", models.PositiveIntegerField(blank=True, null=True)),
                ("organization_result", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Aceptada"),
                            ("DISCREPANCY", "Con discrepancias"),
                            ("ERROR", "Con error"),
                            ("DUPLICATE", "Fila ya importada antes"),
                        ],
                        max_length=16,
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("discrepancies", models.JSONField(blank=True, default=list)),
                ("row_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bat_rows",
                        to="batches.intakebatch",
                    ),
                ),
                (
                    "csv_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="digitization.batcsvimport",
                    ),
                ),
            ],
            options={
                "verbose_name": "fila CSV del BAT",
                "verbose_name_plural": "filas CSV del BAT",
                "ordering": ("row_number",),
            },
        ),
    ]
