# Generated by Django 5.2.17 on 2026-09-06 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("digitization", "0001_initial"),
        ("people", "0002_initial"),
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batcsvrow",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bat_rows",
                to="records.personnelrecord",
            ),
        ),
        migrations.AddField(
            model_name="digitalasset",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="digital_assets",
                to="records.personnelrecord",
            ),
        ),
        migrations.AddField(
            model_name="digitaldocument",
            name="classification_confirmed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="confirmed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="digitaldocument",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="records.personnelrecord",
            ),
        ),
        migrations.AddField(
            model_name="digitalasset",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="digitization.digitaldocument",
            ),
        ),
        migrations.AddField(
            model_name="digitalinventoryrun",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_runs",
                to="records.personnelrecord",
            ),
        ),
        migrations.AddField(
            model_name="digitalinventoryrun",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="applicable_systems",
            field=models.ManyToManyField(
                blank=True,
                related_name="document_types",
                to="people.administrativesystem",
            ),
        ),
        migrations.AddField(
            model_name="digitaldocument",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="digitization.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="scansession",
            name="digitalizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scan_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scansession",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scan_sessions",
                to="records.personnelrecord",
            ),
        ),
        migrations.AddField(
            model_name="digitaldocument",
            name="scan_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="digitization.scansession",
            ),
        ),
        migrations.AddConstraint(
            model_name="batcsvrow",
            constraint=models.UniqueConstraint(
                fields=("csv_import", "row_number"), name="unique_bat_csv_row_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="digitalasset",
            constraint=models.UniqueConstraint(
                fields=("record", "relative_path"), name="unique_asset_path_per_record"
            ),
        ),
        migrations.AddConstraint(
            model_name="digitaldocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scan_mode", "OTHER"), _negated=True),
                    models.Q(("other_mode_description", ""), _negated=True),
                    _connector="OR",
                ),
                name="other_scan_mode_requires_description",
            ),
        ),
    ]
