# Generated by Django 5.2.17 on 2026-09-06 21:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitization", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="digitization.digitalasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "página digital",
                "verbose_name_plural": "páginas digitales",
                "ordering": ("asset", "page_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "page_number"),
                        name="unique_page_number_per_asset",
                    )
                ],
            },
        ),
    ]
