# Generated by Django 5.2.17 on 2026-09-06 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0002_initial"),
        ("people", "0002_initial"),
        ("sources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=40,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9_-]+$",
                                "Use letras, números, guion o guion bajo.",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("blocks_flow", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "tipo de incidencia",
                "verbose_name_plural": "tipos de incidencia",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="PersonnelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("physical_identifier", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Recibido"),
                            ("ASSIGNED", "Asignado"),
                            ("IN_PROGRESS", "En proceso"),
                            (
                                "READY_FOR_REVIEW",
                                "Terminado por digitalizador / Pendiente de validación",
                            ),
                            ("OBSERVED", "Observado para corrección"),
                            ("CORRECTED", "Corrección enviada / Pendiente de revisión"),
                            ("VALIDATED", "Validado"),
                            ("CLOSED", "Cerrado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="RECEIVED",
                        max_length=30,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="batches.intakebatch",
                    ),
                ),
                (
                    "current_custodian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records_in_custody",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declared_systems",
                    models.ManyToManyField(
                        blank=True,
                        related_name="declared_records",
                        to="people.administrativesystem",
                    ),
                ),
                (
                    "expected_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expected_records",
                        to="people.administrativesystem",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="people.person",
                    ),
                ),
                (
                    "source_row",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="sources.payrollsourcerow",
                    ),
                ),
            ],
            options={
                "verbose_name": "expediente",
                "verbose_name_plural": "expedientes",
                "ordering": ("batch", "person__curp"),
                "permissions": [
                    (
                        "view_all_records",
                        "Puede consultar todos los expedientes del área",
                    ),
                    ("assign_record", "Puede asignar y reasignar expedientes"),
                    ("work_on_record", "Puede trabajar expedientes asignados"),
                    ("submit_record", "Puede enviar expedientes a revisión"),
                    ("correct_record", "Puede enviar correcciones a revisión"),
                    ("close_record", "Puede cerrar expedientes validados"),
                    ("cancel_record", "Puede cancelar expedientes con motivo"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("INTAKE", "Recepción"),
                            ("PHYSICAL_COUNT", "Conteo físico"),
                            ("DIGITIZATION", "Digitalización"),
                            ("REVIEW", "Revisión"),
                            ("OTHER", "Otra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Abierta"), ("RESOLVED", "Resuelta")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "detected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detected_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="records.incidenttype",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="records.personnelrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "incidencia",
                "verbose_name_plural": "incidencias",
                "ordering": ("-detected_at",),
            },
        ),
        migrations.CreateModel(
            name="PhysicalCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                ("correction_reason", models.TextField(blank=True)),
                (
                    "counted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physical_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physical_counts",
                        to="records.personnelrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "conteo físico",
                "verbose_name_plural": "conteos físicos",
                "ordering": ("-version",),
            },
        ),
        migrations.CreateModel(
            name="RecordAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "digitalizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digitization_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="records.personnelrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "asignación de expediente",
                "verbose_name_plural": "asignaciones de expedientes",
                "ordering": ("-assigned_at",),
            },
        ),
        migrations.CreateModel(
            name="RecordStatusTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Recibido"),
                            ("ASSIGNED", "Asignado"),
                            ("IN_PROGRESS", "En proceso"),
                            (
                                "READY_FOR_REVIEW",
                                "Terminado por digitalizador / Pendiente de validación",
                            ),
                            ("OBSERVED", "Observado para corrección"),
                            ("CORRECTED", "Corrección enviada / Pendiente de revisión"),
                            ("VALIDATED", "Validado"),
                            ("CLOSED", "Cerrado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Recibido"),
                            ("ASSIGNED", "Asignado"),
                            ("IN_PROGRESS", "En proceso"),
                            (
                                "READY_FOR_REVIEW",
                                "Terminado por digitalizador / Pendiente de validación",
                            ),
                            ("OBSERVED", "Observado para corrección"),
                            ("CORRECTED", "Corrección enviada / Pendiente de revisión"),
                            ("VALIDATED", "Validado"),
                            ("CLOSED", "Cerrado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="records.personnelrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "transición de expediente",
                "verbose_name_plural": "transiciones de expedientes",
                "ordering": ("-occurred_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="personnelrecord",
            constraint=models.UniqueConstraint(
                fields=("batch", "person"), name="unique_person_per_intake_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="physicalcount",
            constraint=models.UniqueConstraint(
                fields=("record", "version"), name="unique_physical_count_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="recordassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("record",),
                name="one_active_assignment_per_record",
            ),
        ),
    ]
