# Generated by Django 5.2.17 on 2026-09-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordassignment",
            name="acceptance_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recordassignment",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
