CREATE TABLE directorio(id INTEGER PRIMARY KEY,tipo TEXT NOT NULL CHECK(tipo IN ('area','persona','sistema','ubicacion')),nombre TEXT NOT NULL,clave TEXT NOT NULL,notas TEXT NOT NULL DEFAULT '',activo INTEGER NOT NULL DEFAULT 1 CHECK(activo IN (0,1)),creado TEXT NOT NULL,actualizado TEXT NOT NULL,UNIQUE(tipo,clave));
CREATE TABLE directorio_alias(tipo TEXT NOT NULL,clave TEXT NOT NULL,directorio_id INTEGER NOT NULL REFERENCES directorio(id),PRIMARY KEY(tipo,clave));
ALTER TABLE folios ADD COLUMN area_id INTEGER REFERENCES directorio(id);
ALTER TABLE folios ADD COLUMN entrega_id INTEGER REFERENCES directorio(id);
ALTER TABLE folios ADD COLUMN recibe_id INTEGER REFERENCES directorio(id);
ALTER TABLE folios ADD COLUMN responsable_id INTEGER REFERENCES directorio(id);
ALTER TABLE trabajos ADD COLUMN digitalizador_id INTEGER REFERENCES directorio(id);
ALTER TABLE asignaciones ADD COLUMN persona_id INTEGER REFERENCES directorio(id);
ALTER TABLE prestamo_items ADD COLUMN ubicacion_id INTEGER REFERENCES directorio(id);
ALTER TABLE prestamo_items ADD COLUMN devolucion_recibe_id INTEGER REFERENCES directorio(id);
ALTER TABLE prestamo_items ADD COLUMN integra_id INTEGER REFERENCES directorio(id);
ALTER TABLE prestamo_items ADD COLUMN sistema_id INTEGER REFERENCES directorio(id);
ALTER TABLE prestamo_items ADD COLUMN integra_declarado TEXT NOT NULL DEFAULT '';
ALTER TABLE prestamo_items ADD COLUMN sistema_declarado TEXT NOT NULL DEFAULT '';
ALTER TABLE prestamo_items ADD COLUMN fecha_solicitud TEXT;
ALTER TABLE prestamo_items ADD COLUMN trabajado_declarado TEXT NOT NULL DEFAULT '';
ALTER TABLE prestamo_items ADD COLUMN numero_lista TEXT NOT NULL DEFAULT '';
ALTER TABLE prestamo_items ADD COLUMN lista_padre_id INTEGER REFERENCES prestamo_items(id);
ALTER TABLE observaciones_revision ADD COLUMN responsable_id INTEGER REFERENCES directorio(id);
CREATE TABLE listas_importadas(id TEXT PRIMARY KEY,fuente_id INTEGER NOT NULL REFERENCES fuentes(id),hoja TEXT NOT NULL,config_hash TEXT NOT NULL,creado TEXT NOT NULL,operador TEXT NOT NULL,resultado TEXT NOT NULL,UNIQUE(fuente_id,hoja,config_hash));
CREATE TABLE lista_registros(id INTEGER PRIMARY KEY,lista_id TEXT NOT NULL REFERENCES listas_importadas(id),origen_id INTEGER NOT NULL REFERENCES origen(id),folio_id INTEGER REFERENCES folios(id),prestamo_item_id INTEGER REFERENCES prestamo_items(id),trabajo_id INTEGER REFERENCES trabajos(id),resultado TEXT NOT NULL,detalle TEXT NOT NULL,UNIQUE(lista_id,origen_id));
CREATE INDEX idx_prestamo_identidad ON prestamo_items(folio_id,curp_esperada,legajo_esperado);
