CREATE TABLE expedientes(id TEXT PRIMARY KEY,curp TEXT NOT NULL CHECK(curp=UPPER(TRIM(curp))),legajo INTEGER NOT NULL CHECK(legajo>0),creado TEXT NOT NULL,origen TEXT NOT NULL,UNIQUE(curp,legajo));
ALTER TABLE folios ADD COLUMN area_origen TEXT NOT NULL DEFAULT '';
ALTER TABLE folios ADD COLUMN entrega TEXT NOT NULL DEFAULT '';
ALTER TABLE folios ADD COLUMN recibe TEXT NOT NULL DEFAULT '';
ALTER TABLE folios ADD COLUMN acuse TEXT NOT NULL DEFAULT '';
ALTER TABLE folios ADD COLUMN recepcion_at TEXT;
ALTER TABLE folios ADD COLUMN recepcion_estado TEXT NOT NULL DEFAULT 'Registrado';
CREATE TABLE prestamo_items(id INTEGER PRIMARY KEY,folio_id INTEGER NOT NULL REFERENCES folios(id),expediente_id TEXT REFERENCES expedientes(id),curp_esperada TEXT NOT NULL,legajo_esperado INTEGER,curp_recibida TEXT,legajo_recibido INTEGER,validacion TEXT NOT NULL DEFAULT 'Pendiente',validado_por TEXT,validado_at TEXT,discrepancia TEXT NOT NULL DEFAULT '',ubicacion_original TEXT NOT NULL DEFAULT '',custodia TEXT NOT NULL DEFAULT 'Registrado',devolucion_at TEXT,devolucion_recibe TEXT,aceptacion_at TEXT,origen TEXT NOT NULL DEFAULT 'Registrado');
ALTER TABLE trabajos ADD COLUMN expediente_id TEXT REFERENCES expedientes(id);
ALTER TABLE trabajos ADD COLUMN prestamo_item_id INTEGER REFERENCES prestamo_items(id);
ALTER TABLE trabajos ADD COLUMN calidad TEXT NOT NULL DEFAULT 'No revisado';
ALTER TABLE trabajos ADD COLUMN prioridad TEXT NOT NULL DEFAULT 'Normal';
ALTER TABLE trabajos ADD COLUMN etiqueta TEXT NOT NULL DEFAULT '';
ALTER TABLE trabajos ADD COLUMN bloqueo TEXT NOT NULL DEFAULT '';
ALTER TABLE trabajos ADD COLUMN fecha_objetivo TEXT;
ALTER TABLE trabajos ADD COLUMN digitales_declarados INTEGER;
ALTER TABLE trabajos ADD COLUMN conciliacion_pendiente INTEGER NOT NULL DEFAULT 0;
ALTER TABLE trabajos ADD COLUMN procedencia TEXT NOT NULL DEFAULT 'Registrado';
CREATE TABLE asignaciones(id INTEGER PRIMARY KEY,trabajo_id INTEGER NOT NULL REFERENCES trabajos(id),folio_id INTEGER REFERENCES folios(id),persona TEXT NOT NULL,rol TEXT NOT NULL,inicio TEXT,fin TEXT,registrado TEXT NOT NULL,operador TEXT NOT NULL,motivo TEXT NOT NULL,origen TEXT NOT NULL);
CREATE TABLE eventos_operativos(id INTEGER PRIMARY KEY,expediente_id TEXT REFERENCES expedientes(id),trabajo_id INTEGER REFERENCES trabajos(id),prestamo_item_id INTEGER REFERENCES prestamo_items(id),evento TEXT NOT NULL,fecha TEXT NOT NULL,operador TEXT NOT NULL,motivo TEXT NOT NULL);
CREATE INDEX idx_ciclo_expediente ON trabajos(expediente_id);
CREATE INDEX idx_prestamo_folio ON prestamo_items(folio_id);
CREATE INDEX idx_asignacion_ciclo ON asignaciones(trabajo_id,fin);
DROP TRIGGER IF EXISTS no_nueva_identidad_duplicada;
