# Generated by Django 5.2.17 on 2026-09-06 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_file", models.FileField(upload_to="source_imports/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Procesando"),
                            ("COMPLETED", "Completada"),
                            ("WITH_ERRORS", "Completada con errores"),
                            ("FAILED", "Fallida"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("accepted_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("warning_rows", models.PositiveIntegerField(default=0)),
                ("column_mapping", models.JSONField(default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "importación de Nóminas",
                "verbose_name_plural": "importaciones de Nóminas",
                "ordering": ("-imported_at",),
                "permissions": [
                    ("import_payroll", "Puede importar archivos oficiales de Nóminas"),
                    (
                        "reconcile_payroll",
                        "Puede conciliar fuente oficial y expedientes",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollSourceRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Aceptada"),
                            ("WARNING", "Aceptada con advertencias"),
                            ("ERROR", "Con error"),
                        ],
                        max_length=12,
                    ),
                ),
                ("curp_raw", models.CharField(blank=True, max_length=255)),
                (
                    "normalized_curp",
                    models.CharField(blank=True, db_index=True, max_length=18),
                ),
                ("full_name", models.CharField(blank=True, max_length=250)),
                ("employment_status_raw", models.CharField(blank=True, max_length=100)),
                ("systems_payload", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("row_fingerprint", models.CharField(max_length=64)),
                (
                    "payroll_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="sources.payrollimport",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_rows",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "fila de fuente oficial",
                "verbose_name_plural": "filas de fuente oficial",
                "ordering": ("row_number",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payroll_import", "row_number"),
                        name="unique_payroll_import_row_number",
                    )
                ],
            },
        ),
    ]
