# Generated by Django 5.2.17 on 2026-09-06 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batches", "0002_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakebatch",
            name="source_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intake_batches",
                to="sources.payrollimport",
            ),
        ),
    ]
