# Generated by Django 5.2.17 on 2026-09-06 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("OBSERVED", "Devolver con observaciones"),
                            ("VALIDATED", "Validar"),
                        ],
                        max_length=10,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "verified_physical_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "verified_digital_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "verified_individual_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "verified_multi_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("discrepancies", models.JSONField(blank=True, default=list)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_reviews",
                        to="records.personnelrecord",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "revisión de calidad",
                "verbose_name_plural": "revisiones de calidad",
                "ordering": ("-reviewed_at",),
                "permissions": [
                    ("observe_record", "Puede devolver expedientes con observaciones"),
                    ("validate_record", "Puede validar expedientes"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("decision", "OBSERVED"), _negated=True),
                            models.Q(("observations", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="observed_review_requires_notes",
                    )
                ],
            },
        ),
    ]
