# Generated by Django 5.2.17 on 2026-09-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_operational_reports", "Puede consultar reportes operativos")
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
